# Generated by Django 3.2 on 2023-04-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("u", "Аутентифицированный пользователь"),
                    ("m", "Модератор"),
                    ("a", "Администратор"),
                ],
                default="u",
                max_length=1,
            ),
        ),
    ]
